version: '3'

services:
    augment:
        build: .
        user: ${CURRENT_UID}
        command: python3.7 /usr/scripts/augment.py
        volumes:
            - ./scripts:/usr/scripts:ro
            - ./dataset:/usr/dataset:ro
            - ./dataset-augmented:/usr/dataset-augmented
        environment: 
            AUG_NB_AUGMENTATION_PER_IMAGE: 5